project:
  type: default
date: last-modified
format:
  html:
    code-copy: true
    code-fold: true
    code-overflow: wrap
    code-tools: true
    df-print: paged
    embed-resources: true
    smooth-scroll: true
    grid:
      sidebar-width: 278px
      body-width: 900px
      margin-width: 278px
highlight-style: ayu-dark
knitr:
  opts_chunk:
    dev: "ragg_png"
number-sections: true
reference-location: document
theme: flatly
title-block-banner: true
toc: true
toc-location: left
toc-expand: true
